<div class="faceBox">
    <div class="uploadBox">
        <form name="uploadForm">
            <input id="file_upload" name="file_upload" type="file" />
        </form>
    </div>
    <div class="ImgBox">
        <img id="preview" src="<?php echo $this->config->url->img, $category->face_url; ?>" width="100" height="100" />
    </div>
    <button id="jcropBtn" class="icons btns" data-url="" title="裁剪图片">裁 剪</button>
</div>

<div class="abox">
    <div class="prompt"></div>
    <form id="id_categoryForm" method="post" action="<?php echo $this->url->get('backend/saveCategory'); ?>" onsubmit="return false;">
    <div class="form_items">
        <label class="items">标题：</label>
        <input id="id_title" type="text" name="info[title]" class="ins normal" maxlength="20" min="2" max="20" nullmsg="请输入标题。" errormsg="由2到20个字符组成。" value="<?php echo $category->title; ?>" />
        <em id="id_title_msg"></em>
    </div>
    <div class="form_items">
        <label class="items">关键字：</label>
        <input type="text" name="info[keywords]" class="ins normal" value="<?php echo $category->keywords; ?>" />
    </div>
    <div class="form_items">
        <label class="items">简介：</label>
        <input id="id_content" type="text" name="info[description]" class="ins ins300" value="<?php echo $category->description; ?>" />
        <p>还可以输入 <span id="max_words" class="fred">24</span> 字符</p>
    </div>
    <div class="form_items">
        <label class="items">排序：</label>
        <input type="text" name="info[sort]" class="ins ins50" value="<?php echo $category->sort; ?>" />
    </div>
    <div class="form_items">
        <label class="items">条目数：</label>
        <input type="text" name="info[numbers]" class="ins ins50" value="<?php echo $category->numbers; ?>" />
    </div>
    <div class="form_items pl80">
        <input type="hidden" id="face_url" name="info[face_url]" value="<?php echo $category->face_url; ?>" />
        <input type="hidden" name="info[id]" value="<?php echo $category->id; ?>" />
        <button id="id_save_btn" type="submit" class="icons btns" locked-msg="提交中...">保 存</button>
    </div>
    </form>
    <br class="clear" />
</div>
<script type="text/javascript">
    var component = ["cptCategoryFun"];
</script>