<div class="abox">
    <table class="table">
    <thead>
        <tr>
            <th>标题</th>
            <th>主播</th>
            <th>来源</th>
            <th>状态</th>
            <th>发布时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($records as $record): ?>
        <tr>
            <td><?php echo $record->title; ?></td>
            <td><?php echo $record->anchor; ?></td>
            <td><?php echo $record->comeform; ?></td>
            <td><?php echo $record->status ? '停播' : '开播'; ?></td>
            <td><?php echo $record->create_time; ?></td>
            <td><a href="<?php echo $this->url->get('backend/editFm/' . $record->id); ?>">修改</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
    <div class="pagination pagination-centered"><?php echo $pagenav;?></div>
</div>