<div class="abox">
    <table class="table">
    <thead>
        <tr>
            <th>标题</th>
            <th>来源</th>
            <th>状态</th>
            <th>发布时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($records as $record): ?>
        <tr>
            <td><?php echo $record->title; ?></td>
            <td><?php echo $record->comeform; ?></td>
            <td><?php echo $record->status ? '公开' : '不公开'; ?></td>
            <td><?php echo $record->create_time; ?></td>
            <td>
                <a href="<?php echo $this->url->get('backend/tourphoto/' . $record->id); ?>">详情</a>
                <a href="<?php echo $this->url->get('backend/editTour/' . $record->id); ?>">修改</a>
                <a class="delTour" data-pk="<?php echo $record->id; ?>" href="javascript:;">删除</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
    <div class="pagination pagination-centered"><?php echo $pagenav;?></div>
</div>