<!--Main{-->
<div class="wrap main" id="user_status" admin="<?php echo (int)$isAdmin; ?>">
    <div class="mleft fl">
    <?php if( $isAdmin ): ?>
        <div class="ins_box">
            <div class="ins_show" id="care_ins_box">
                <form id="id_sharedForm" method="post" action="<?php echo $this->url->get('shared/add'); ?>" onsubmit="return false;">
                <span class="max_ins_word">你还可以输入<span id="max_words">140</span>个字</span>
                <textarea class="care_ins" id="id_content" name="content"></textarea>
                <div class="grey_icon icons btns sbtns">发 表</div>
                <div class="ins_focus">
                    <div class="focus_txt">
                        <select name="category" id="id_category" class="select">
                            <option value="">请选择类别</option>
                        <?php foreach($categorys as $category): ?>
                            <option value="<?php echo $category['id']; ?>"><?php echo $category['title']; ?></option>
                        <?php endforeach; ?>
                        </select>
                        <a target="_blank" class="ml10 tal" href="<?php echo $this->url->get('backend/addCategory'); ?>" title="新增类别">新增</a>
                    </div>
                    同步到：<input type="checkbox" name="istop" value="1" /> 首页
                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />
                    <button id="id_shared_btn" type="submit" class="icons btns ml10" lockedMsg="发表中...">发 表</button>
                </div>
                </form>
            </div>
        </div>
        <!--输入框-->
    <?php endif; ?>

        <div class="carelist facecare mt20" id="id_sharedList" cid="<?php echo $curr_category; ?>"></div>
    </div>

    <div class="mright fl">
        <?php echo $this->partial('common/group'); ?>

        <div class="rt mt20">
            <?php echo Lang::tip('TShared'); ?>分类
            <span class="more"><a version="1.0" class="qzOpenerDiv" href="http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_likeurl" target="_blank">赞</a></span>
        </div>
        <?php echo $this->partial('common/category'); ?>
    </div>
    <br class="clear" />
</div>
<!--}Main{-->

<script  src="http://qzonestyle.gtimg.cn/qzone/app/qzlike/qzopensl.js#jsdate=20111107&style=2&showcount=1&width=130&height=30" charset="utf-8" defer="defer" ></script>

<script type="text/javascript">
    var component = ["cptSharedList"];
</script>