<?php foreach($shareds as $row): ?>
<div class="items" id="id_shared_<?php echo $row['id']; ?>">
    <div class="care_user">
        <span class="face">
            <span class="icons bgs"></span>
            <img alt="<?php echo $row['category_name']; ?>" src="<?php echo $this->config->url->img, $row['category_face']; ?>!50" height="50" width="50" />
        </span>
        <p><?php echo $row['category_name']; ?></p>
    </div>
    <div class="care_box w575">
        <div class="desc"><?php echo $row['content']; ?></div>
        <div class="care_tool">
            <?php echo $row['create_time']; ?></a>
            <!--<span class="share_tool">
                <span class="sline hidden">|</span>
                <span class="tool_area"></span>
            </span>-->
            <span class="pos">
            <?php if( $isLogin ): ?>
                <a class="change_class" href="javascript:;" data-url="<?php echo $this->url->get('shared/changeCategory/' . $row['id']); ?>" title="重置分类">移动</a>
                <a href="javascript:;" onclick="return delShared(<?php echo $row['id']; ?>, <?php echo $row['category_id']; ?>);">删除</a>
            <?php endif; ?>
            </span>
        </div>
    </div>
</div>
<?php endforeach; ?>