<div class="abox">
    <div class="prompt"></div>
    <form id="id_password_form" action="<?php echo $this->url->get('account/savePassword'); ?>" method="post" onsubmit="return false;">
    <div class="form_items">
        <label class="items">旧密码：</label>
        <input type="password" id="id_oldPasswd" name="old_password" class="ins" maxlength="16" tabindex="1" min="4" max="16" nullmsg="请输入旧密码。" errormsg="由4到16个字符组成。" placeholder="旧密码" />
        <em id="id_oldPasswd_msg"></em>
    </div>
    <div class="form_items">
        <label class="items">新密码：</label>
        <input type="password" id="id_newPasswd" name="new_password" class="ins" maxlength="16" tabindex="2" min="4" max="16" nullmsg="请输入新密码。" errormsg="由4到16个字符组成。" placeholder="新密码" />
        <em id="id_newPasswd_msg"></em>
    </div>
    <div class="form_items">
        <label class="items">确认新密码：</label>
        <input type="password" id="id_cfmPasswd" name="cfm_password" class="ins" maxlength="16" tabindex="3" datatype="recheck" recheck="#id_newPasswd" errormsg="两次密码输入不相同。" />
        <em id="id_cfmPasswd_msg"></em>
    </div>
    <div class="form_items pl80">
        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />
        <button id="id_save_btn" type="submit" class="icons btns" locked-msg="提交中..." tabindex="4">保 存</button>
    </div>
    </form>
</div>
<script type="text/javascript">
    var component = ["cptSetPasswdFun"];
</script>