<?php if($isLogin): ?>
<div class="uploadBox">
    <form name="uploadForm">
        <input id="file_upload" name="file_upload" type="file" />
    </form>
    <div class="uploadTip">1440 x 900</div>
    <input id="newBg" type="hidden" />
    <button id="saveBg" class="btnIcon smallbtn ml20 hidden">保 存</button>
</div>
<?php endif; ?>

<script type="text/javascript">
    var isLogin = "<?php echo intval($isLogin); ?>";
</script>