<!--Main{-->
<div class="wrap main">
    <div class="mleft fl">
        <div class="carelist zinecare mt20" id="id_zineList" cid="<?php echo $curr_category; ?>"></div>
    </div>

    <div class="mright fl">
        <?php echo $this->partial('common/group'); ?>

        <div class="rt mt20"><?php echo Lang::tip('TMagazine'); ?>分类</div>
        <?php echo $this->partial('common/category'); ?>
    </div>
    <br class="clear" />
</div>
<!--}Main{-->

<script type="text/javascript">
    var isLogin = "<?php echo ($isLogin); ?>";
    var component = ["cptMagazineList"];
</script>