<!--Main{-->
<div class="wrap main">
    <div class="mleft fl mw660">
        <div class="show_box">
            <div class="local">
                当前位置：
                <a class="mlt5" href="<?php echo $this->url->get('magazine'); ?>"><?php echo Lang::tip('TMagazine'); ?></a>&gt;
                <a class="mlt5" href="<?php echo $this->url->get('magazine_' . $zine->category_id); ?>"><?php echo $zine->category_name; ?></a>&gt;
                <span class="mlt5">文章正文</span>
                <span id="qzineShare" class="sharetool"></span>
            </div>
            <div class="show_title">
                <h2><?php echo $zine->title; ?></h2>
                <span>发布于：<?php echo $zine->create_time; ?></span>
                <span class="ml10">阅读：<?php echo $zine->access_times; ?></span>
                <?php if($zine->comeform): ?>
                <span class="ml10">来源：
                <?php if($zine->form_url): ?>
                    <a target="_blank" href="<?php echo $zine->form_url; ?>"><?php echo $zine->comeform; ?></a>
                <?php else: ?>
                    <?php echo $zine->comeform; ?>
                <?php endif; ?>
                </span>
                <?php endif; ?>
                <?php if($isAdmin): ?>
                <span class="pos">
                    <a target="_blank" href="<?php echo $this->url->get('backend/editMagazine/' . $zine->id); ?>">修改</a>
                </span>
                <?php endif; ?>
            </div>
            <div class="show_content">
                <p>导读：<?php echo $zine->description; ?></p>
                <div class="tac mb20 mt20"><img class="show_img" alt="<?php echo $zine->title; ?>" src="<?php echo $this->config->url->img, $zine->face_url; ?>" /></div>
                <?php echo $zine->content; ?>
                <div class="bdsharebuttonbox mt20"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
            </div>
        </div>
        <!--showbox-->
        <div class="prevnext">
            <span class="fgrey">上一篇：</span>
            <?php if(!empty($preZine)): ?>
            <a class="prev" title="<?php echo $preZine->title; ?>" href="<?php echo $this->url->get('magazine@' . $preZine->id); ?>"><?php echo $preZine->title; ?></a>
            <?php endif; ?>
  
            <span class="r">
                <span class="fgrey">下一篇：</span>
                <?php if(!empty($nextZine)): ?>
                <a class="next" title="<?php echo $nextZine->title; ?>" href="<?php echo $this->url->get('magazine@' . $nextZine->id); ?>"><?php echo $nextZine->title; ?></a>
                <?php endif; ?>
            </span>
        </div>
        <!--上下篇-->

    </div>

    <div class="mright fl mpl">
        <?php echo $this->partial('common/group'); ?>

        <?php if($isAdmin): ?>
        <a target="_blank" class="fbtn mt20" href="<?php echo $this->url->get('backend/addMagazine'); ?>"><?php echo Lang::tip('TAddMagazine'); ?></a>
        <?php endif; ?>
    </div>
    <br class="clear" />
</div>
<!--}Main{-->

<script type="text/javascript">
    (function(){
    var p = {
        url:location.href,
        showcount:'1',
        summary:'<?php echo $zine->description; ?>',
        title:'<?php echo $zine->title; ?>',
        site:'<?php echo $this->config->application->title; ?>',
        pics:'<?php echo $this->config->url->img, $zine->face_url; ?>',
        style:'102',
        width:145,
        height:30
    };
    var s = [];
    for(var i in p){
        s.push(i + '=' + encodeURIComponent(p[i]||''));
    }
    document.getElementById("qzineShare").innerHTML = ['<a version="1.0" class="qzOpenerDiv" href="http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?',s.join('&'),'" target="_blank">分享</a>'].join('');
    })();
</script>
<script src="http://qzonestyle.gtimg.cn/qzone/app/qzlike/qzopensl.js#jsdate=20111201" charset="utf-8"></script>


<script>
window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"32"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>