<!--Main{-->
<div class="wrap main">
    <div class="mleft fl mw660">
        <div class="show_box">
            <div class="local">
                当前位置：
                <a class="mlt5" href="<?php echo $this->url->get('notebook'); ?>"><?php echo Lang::tip('TNotebook'); ?></a>&gt;
                <a class="mlt5" href="<?php echo $this->url->get('notebook_' . $note->category_id); ?>"><?php echo $note->category_name; ?></a>&gt;
                <span class="mlt5">文章正文</span>
                <span id="qzineShare" class="sharetool"></span>
            </div>
            <div class="show_title">
                <h2><?php echo $note->title; ?></h2>
                <span>发布于：<?php echo $note->create_time; ?></span>
                <span class="ml10">阅读：<?php echo $note->access_times; ?></span>
                <?php if($note->comeform): ?>
                <span class="ml10">来源：
                <?php if($note->form_url): ?>
                    <a target="_blank" href="<?php echo $note->form_url; ?>"><?php echo $note->comeform; ?></a>
                <?php else: ?>
                    <?php echo $note->comeform; ?>
                <?php endif; ?>
                </span>
                <?php endif; ?>
                <?php if($isAdmin): ?>
                <span class="pos">
                    <a target="_blank" href="<?php echo $this->url->get('backend/editNote/' . $note->id); ?>">修改</a>
                </span>
                <?php endif; ?>
            </div>
            <div class="show_content">
                <?php echo $note->content; ?>
                <div class="bdsharebuttonbox mt20"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
            </div>
        </div>
        <!--showbox-->
        
        <div class="prevnext">
            <span class="fgrey">上一篇：</span>
            <?php if(!empty($preNote)): ?>
            <a class="prev" title="<?php echo $preNote->title; ?>" href="<?php echo $this->url->get('magazine@' . $preNote->id); ?>"><?php echo $preNote->title; ?></a>
            <?php endif; ?>
  
            <span class="r">
                <span class="fgrey">下一篇：</span>
                <?php if(!empty($nextNote)): ?>
                <a class="next" title="<?php echo $nextNote->title; ?>" href="<?php echo $this->url->get('magazine@' . $nextNote->id); ?>"><?php echo $nextNote->title; ?></a>
                <?php endif; ?>
            </span>
        </div>
    </div>

    <div class="mright fl mpl">
        <?php echo $this->partial('common/group'); ?>
        
        <?php if($isAdmin): ?>
        <a target="_blank" class="fbtn mt20" href="<?php echo $this->url->get('backend/addNote'); ?>"><?php echo Lang::tip('TAddNote'); ?></a>
        <?php endif; ?>
    </div>
    <br class="clear" />
</div>
<!--}Main{-->

<script type="text/javascript">
    (function(){
    var p = {
        url:location.href,
        showcount:'1',
        summary:'<?php echo $note->description; ?>',
        title:'<?php echo $note->title; ?>',
        site:'<?php echo $this->config->application->title; ?>',
        style:'102',
        width:145,
        height:30
    };
    var s = [];
    for(var i in p){
        s.push(i + '=' + encodeURIComponent(p[i]||''));
    }
    document.getElementById("qzineShare").innerHTML = ['<a version="1.0" class="qzOpenerDiv" href="http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?',s.join('&'),'" target="_blank">分享</a>'].join('');
    })();
</script>
<script src="http://qzonestyle.gtimg.cn/qzone/app/qzlike/qzopensl.js#jsdate=20111201" charset="utf-8"></script>

<script>
window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"32"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>