<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="created" content="<?php echo date('YmdHis'); ?>">
    <title>抱歉，出错了- <?php echo $this->config->application->title; ?></title>
    <link href="<?php echo $this->config->url->assets; ?>/images/favicon.ico" rel="SHORTCUT ICON" />
    <style type="text/css">
	<!--
	body{
		margin:0;
		padding:0;
		font:12px/1.5 'Microsoft Yahei', Arial, Helvetica, sans-serif, '宋体';
		color:#444;
		background:#E2E2E2
	}
	#main{
		margin:60px auto 0;
		padding:250px 80px 0 320px;
		width:400px;
		height:310px;
		background:url(<?php echo $this->config->url->assets; ?>/images/404.gif) no-repeat
	}
	#main h1{
		margin:0;
		padding:0;
		border-bottom:1px solid #E2E2E2;
		font-size:22px;
		font-weight:lighter;
		color:#111
	}
	#main .msgs{
		padding-top:5px;
		border-top:1px solid #C5C5C5;
		line-height:24px;
	}
	#main a{color:#369;text-decoration:none}
	#main a:hover{text-decoration:underline}
	-->
	</style>
</head>
<body>
<div id="main">
	<?php echo $this->getContent(); ?>
</div>
</body>
</html>