<?php

return array(
    // tip
    'TUserLogin' => '用户登录',
    'TEditAccount' => '我的账号',
    'TEditPassword' => '密码设置',
    'TBoard' => '公告',
    'TAddBoard' => '发布公告',
    'TEditBoard' => '编辑公告',
    'TCategory' => '分类',
    'TAddCategory' => '新增分类',
    'TEditCategory' => '编辑分类',
    'TAddNote' => '发布笔记',
    'TEditNote' => '编辑笔记',
    'TAddMagazine' => '发布杂志',
    'TEditMagazine' => '编辑杂志',
    'TAddFM' => '发布FM',
    'TEditFM' => '编辑FM',
    'TAddTour' => '发布旅游主题',
    'TEditTour' => '编辑旅游主题',
    'TCacheList' => 'cache清单',
    'TBackdrop' => '背景墙',
    'TMember' => '会员信息',
    'TFm' => 'FM',
    'TShared' => '语录',
    'TNotebook' => '笔记',
    'TMagazine' => '杂志',
    'TTour' => '旅游',
    'TGuestbook' => '留言板',
    'TAdd' => '新增',
    'TPublish' => '发布',
    
    // success
    'SLogin' => '登录成功。',
    'SLogout' => '账号退出成功。',
    'SPublish' => '发布成功。',
    'SUpdate' => '更新成功。',
    'SDelete' => '删除成功。',
    
    // error
    'ESystemError' => '系统错误，请稍后再试。',
    'ETokenError' => 'Token验证失败，请重新刷新页面。',
    'EFormSubmit' => '表单提交错误，请重新刷新页面。',
    'EAjaxSubmit' => '数据提交方式错误，请重新刷新页面。',
    'EParamError' => '参数错误，请确认。',
    'EQQRegError' => 'QQ信息更新失败。',
    
    'EAccountIsEmpty' => '请输入账号。',
    'EUserNotExist' => '账号不存在。',
    'EPasswordIsEmpty' => '请输入密码。',
    'ENewPasswordIsEmpty' => '请输入新密码。',
    'EOldPasswordIsEmpty' => '请输入旧密码。',
    'EPasswordError' => '密码错误。',
    'EPasswordNotMatch' => '旧密码错误。',
    'EVerifyCodeError' => '验证码输入不正确。',
    'ENotLogin' => '请您先登录。',
    'ELoginTimeout' => '登录超时，请重新登录。',
    'EAuthInfoFailed' => '身份验证信息失效。',

    'EShareIsEmpty' => '请输入内容。',
    'EShareNotExist' => '此内容不存在。',
    'ECategoryIsEmpty' => '请选择类别。',
    'EChannelIsEmpty' => '频道错误，请确认。',
    
);