<?php foreach($records as $record): ?>
    <dd id="id_reply_<?php echo $record['id']; ?>">
        <img alt="<?php echo $record['nickname']; ?>" src="<?php echo $this->config->url->img, $record['face']; ?>!30" height="30" width="30">
        <?php echo $record['nickname']; ?> ：
        <?php if( $this->userIdentity->isAdmin() || $this->userIdentity->getUin() == $record['uin'] ): ?>
        <a onclick="delGbookReply(<?php echo $record['id']; ?>, <?php echo $record['parent_id']; ?>);" href="javascript:;">删除</a>
        <?php endif; ?>
        <span class="date"><?php echo $record['create_time']; ?></span>
        <p><?php echo $record['content']; ?></p>
    </dd>
<?php endforeach; ?>